### ISSUE TITLE
Provide better exception when issuer doesn't match (common issue when switching between issuers or  Okta Authorization Servers)

### ISSUE THREAD

**Issue by reste85** [okta/okta-jwt-verifier-java#13]
Here the exception stacktrace:

```
com.okta.jwt.JoseException: Failed to validate JWT string
	at com.okta.jwt.impl.NimbusJwtVerifier.decode(NimbusJwtVerifier.java:82)
	at com.okta.jwt.impl.NimbusJwtVerifier.decodeAccessToken(NimbusJwtVerifier.java:68)
	at com.cuebiq.apigateway.handler.OktaAuthHandler.handle(OktaAuthHandler.kt:23)
	at com.cuebiq.apigateway.handler.OktaAuthHandler.handle(OktaAuthHandler.kt:11)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:155)
	at io.vertx.reactivex.ext.web.Route$1.handle(Route.java:153)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:219)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:120)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:133)
	at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
	at io.vertx.reactivex.ext.web.Router.accept(Router.java:94)
	at com.cuebiq.apigateway.verticle.ApiGatewayVerticle$startHttpServer$1.invoke(ApiGatewayVerticle.kt:75)
	at com.cuebiq.apigateway.verticle.ApiGatewayVerticle$startHttpServer$1.invoke(ApiGatewayVerticle.kt:20)
	at com.cuebiq.apigateway.verticle.ApiGatewayVerticleKt$sam$Handler$4b7b53e4.handle(ApiGatewayVerticle.kt)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:111)
	at io.vertx.reactivex.core.http.HttpServer$1.handle(HttpServer.java:109)
	at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:454)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:144)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:669)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:622)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:970)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.<clinit>(DefaultJWTProcessor.java:100)
	at com.okta.jwt.JwtHelper.build(JwtHelper.java:92)
	at com.cuebiq.apigateway.handler.OktaAuthHandler.handle(OktaAuthHandler.kt:19)
	... 45 more
```

**Root cause seems to be: Signed JWT rejected: Another algorithm expected, or no matching key(s)**

Here my configuration of JWTVerifier:
        val jwtVerifier = JwtHelper()
            .setIssuerUrl("https://dev-826799.oktapreview.com/oauth2/default")
            .setAudience("api://default")  // defaults to 'api://default'
            .setConnectionTimeout(1000)    // defaults to 1000ms
            .setReadTimeout(1000)          // defaults to 1000ms
            .setClientId("0oafjb9h4f3lcTja20h7") // optional
            .build()

what's happening?

**Comment by bdemers** [comment]
What does the decoded token look like if you run it through something like: https://www.jsonwebtoken.io/

**Comment by bdemers** [comment]
@reste85 please reopen if this is still an issue!

**Comment by ankit-learns** [comment]
@bdemers I'm still getting the exception. My configuration is similar to above mentioned reste85's.
Following is how my decoded JWT looks like:
{
 "ver": 1,
 "jti": "AT.XmiaE06ohkMmjQg669O4MtP9989_eB-nYbc2ztSG9ag",
 "iss": "https://dev-******.oktapreview.com",
 "aud": "https://dev-******.oktapreview.com",
 "sub": "ankitkumar@********.com",
 "iat": 1537785073,
 "exp": 1537788673,
 "cid": "0oaemdthg7eUYKQ9C0h7",
 "uid": "00ueoibonaFxFA6yP0h7",
 "scp": [
  "profile",
  "groups",
  "openid",
  "email"
 ]
}

PS: I've masked my org data.

**Comment by Hammond95** [comment]
@reste85 Did you solved this?

**Comment by bdemers** [comment]
@Hammond95 usually this is a configuration error. What does your config look like?

**Comment by arvindkrishnakumar-okta** [comment]
Closing this due to inactivity, feel free to reopen if followup is needed.
