### ISSUE TITLE
NoClassDefFoundError after upgrade

### ISSUE THREAD

**Issue by rtveitch** [okta/okta-jwt-verifier-java#135]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Upgrading from `0.5.4` -> `0.5.5` results in a `NoClassDefFoundError`

### Expected behavior

Behavior remains unchanged.

### What went wrong?

The following stacktrace illustrates the issue, related to exclusion of the kotlin stdlib in #130 
```java
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
 at okhttp3.ConnectionPool.<init>(ConnectionPool.kt)
 at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
 at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
 at com.okta.commons.http.okhttp.OkHttpRequestExecutor.createOkHttpClient([OkHttpRequestExecutor.java:73]
 at com.okta.commons.http.okhttp.OkHttpRequestExecutor.([OkHttpRequestExecutor.java:62]
 at com.okta.commons.http.okhttp.OkHttpRequestExecutorFactory.create([OkHttpRequestExecutorFactory.java:58]
 at com.okta.jwt.impl.http.OktaCommonsHttpClient.createRequestExecutor([OktaCommonsHttpClient.java:67]
 at com.okta.jwt.impl.http.OktaCommonsHttpClient.([OktaCommonsHttpClient.java:47]
 at com.okta.jwt.impl.jjwt.BaseVerifierBuilderSupport.httpClient([BaseVerifierBuilderSupport.java:182]
 at com.okta.jwt.impl.jjwt.BaseVerifierBuilderSupport.signingKeyResolver([BaseVerifierBuilderSupport.java:166]
 at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build([JjwtAccessTokenVerifierBuilder.java:58]
 at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build([JjwtAccessTokenVerifierBuilder.java:27]
```

### Steps to reproduce

Upgrade to `0.5.5` and create an `AccessTokenVerifier` something like:

```java
final String issuer = "https://my-oauth-domain/oauth2/default";
final AccessTokenVerifier.Builder builder = JwtVerifiers.accessTokenVerifierBuilder().setIssuer(issuer);
this.verifier = builder.build();
```

Explicitly re-adding the kotlin stdlib as a direct dependency in the project restores the original behavior, e.g.
```xml
<dependency>
  <groupId>org.jetbrains.kotlin</groupId>
  <artifactId>kotlin-stdlib</artifactId>
  <version>1.7.20</version>
</dependency>
```

### Library Version
`0.5.5`

**Comment by arvindkrishnakumar-okta** [comment]
Can you try the latest `0.5.6`?

**Comment by rtveitch** [comment]
Just tried with `0.5.6` and I see the same stacktrace

```java
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
 at okhttp3.ConnectionPool.<init>(ConnectionPool.kt)
 at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
 at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
 at com.okta.commons.http.okhttp.OkHttpRequestExecutor.createOkHttpClient([OkHttpRequestExecutor.java:73]
 at com.okta.commons.http.okhttp.OkHttpRequestExecutor.([OkHttpRequestExecutor.java:62]
 at com.okta.commons.http.okhttp.OkHttpRequestExecutorFactory.create([OkHttpRequestExecutorFactory.java:58]
 at com.okta.jwt.impl.http.OktaCommonsHttpClient.createRequestExecutor([OktaCommonsHttpClient.java:67]
 at com.okta.jwt.impl.http.OktaCommonsHttpClient.([OktaCommonsHttpClient.java:47]
 at com.okta.jwt.impl.jjwt.BaseVerifierBuilderSupport.httpClient([BaseVerifierBuilderSupport.java:182]
 at com.okta.jwt.impl.jjwt.BaseVerifierBuilderSupport.signingKeyResolver([BaseVerifierBuilderSupport.java:166]
 at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build([JjwtAccessTokenVerifierBuilder.java:58]
 at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build([JjwtAccessTokenVerifierBuilder.java:27]
...
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
 at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass([BuiltinClassLoader.java:641]
 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass([ClassLoaders.java:188]
 at java.base/java.lang.ClassLoader.loadClass([ClassLoader.java:520]
```

**Comment by arvindkrishnakumar-okta** [comment]
@rtveitch https://github.com/okta/okta-jwt-verifier-java/pull/137 should fix this issue. Let me know otherwise.

**Comment by rveitch-Ocient** [comment]
Works locally for me!
