### ISSUE TITLE
java.lang.IllegalArgumentException: A signing key must be specified if the specified JWT is digitally signed.

### ISSUE THREAD

**Issue by hackwithharsha** [okta/okta-jwt-verifier-java#162]
Hi Team, 

I am facing the following issue. Tried an existing issue that has already been reported #41 

java.lang.IllegalArgumentException: A signing key must be specified if the specified JWT is digitally signed.
	at io.jsonwebtoken.lang.Assert.notNull(Assert.java:82)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:370)
	at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:529)
	at io.jsonwebtoken.impl.ImmutableJwtParser.parse(ImmutableJwtParser.java:153)
	at com.okta.jwt.impl.jjwt.TokenVerifierSupport.decode(TokenVerifierSupport.java:81)
	at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifier.decode(JjwtAccessTokenVerifier.java:56)

Version : 0.5.7

In the following method, while calling `decode` It is raising Exception.

```java
    AccessTokenVerifier jwtVerifier = JwtVerifiers.accessTokenVerifierBuilder()
            .setIssuer("https://xxx.oktapreview.com")
            .setConnectionTimeout(Duration.ofSeconds(1))
            .setRetryMaxAttempts(2)
            .setRetryMaxElapsed(Duration.ofSeconds(10)) 
            .build();

      Jwt token = jwtVerifier.decode(accessToken);
      Map<String, Object> claims = token.getClaims();
```

Keys are available at **https://xxx.oktapreview.com/oauth2/v1/keys**

Here are the access token header

```json
{
  "kid": "luB6QAwA61nqEH0OFciXlg9myGtws65Phkkhu31528w",
  "alg": "RS256"
}
```

Here is the access token body

```json
{
  "ver": 1,
  "jti": "AT.mKmgFqQpOOpW75uZ3YXtPoB_E--GYluSJX6IDHKCCqg",
  "iss": "https://xxx.oktapreview.com",
  "aud": "https://xxx.oktapreview.com",
  "sub": "hackwithharsha@xxx.com",
  "iat": 1697363867,
  "exp": 1697367467,
  "cid": "xxxxxxxx",
  "uid": "00unqjlabfCX7HQYD0h7",
  "scp": [
    "openid",
    "email",
    "profile"
  ],
  "auth_time": 1697363862
}
```

Issuer is the same in the accessToken body and configuration in AccessTokenVerifier unlike #41 

am I doing anything wrong here or any assumptions which I can try?

**Comment by hackwithharsha** [comment]
Tagging @arvindkrishnakumar-okta  @mariovillaplana-okta  @balathiruvalluvan-okta  @philvanderlinden-okta 

If possible, please provide some suggestions on how to resolve this issue..

**Comment by hackwithharsha** [comment]
Got the issue. But not sure, how to solve it.

In the AccessToken:  keyId mentioned as `luB6QAwA61nqEH0OFciXlg9myGtws65Phkkhu31528w`

```json
{
  "kid": "luB6QAwA61nqEH0OFciXlg9myGtws65Phkkhu31528w",
  "alg": "RS256"
}
```

However, In the keys endpoint `https://xxx.oktapreview.com/oauth2/v1/keys`

```json
"kid": "vseKSVlZNUY2PHzwJtrjzkopC-JW2NQ2ibZ974LiEa4",
```

```json
"kid": "w9Zg-FbKPgA-o9KXHOyAtz_3JA9HBxCpDdgZE-s2gKQ",
```

There is no such key in keys endpoints.. A better error or exception message could have been easier.

My keys endpoint configured by okta_jwt_verifier library as `ISSUER + /oauth2/v1/keys`

Is there any wrong configuration?
