### ISSUE TITLE
NoClassDefFoundError after upgrade

### ISSUE THREAD

**Issue by nishant-mehta** [okta/okta-jwt-verifier-java#172]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests only.

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Describe your issue or request here (if necessary).

### Expected behavior

What should have happened? 

Upgrading from 0.5.1 to 0.5.7 and sprint boot upgrade 3.x should work fine.
No change in behavior.

### What went wrong?

I see build compilations when running the tests.

Error
`kotlin/jvm/internal/Intrinsics`

Stacktrace:
```
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.okta.commons.http.okhttp.OkHttpRequestExecutor.createOkHttpClient(OkHttpRequestExecutor.java:73)
	at com.okta.commons.http.okhttp.OkHttpRequestExecutor.<init>(OkHttpRequestExecutor.java:62)
	at com.okta.commons.http.okhttp.OkHttpRequestExecutorFactory.create(OkHttpRequestExecutorFactory.java:58)
	at com.okta.jwt.impl.http.OktaCommonsHttpClient.createRequestExecutor(OktaCommonsHttpClient.java:67)
	at com.okta.jwt.impl.http.OktaCommonsHttpClient.<init>(OktaCommonsHttpClient.java:47)
	at com.okta.jwt.impl.jjwt.BaseVerifierBuilderSupport.httpClient(BaseVerifierBuilderSupport.java:182)
	at com.okta.jwt.impl.jjwt.BaseVerifierBuilderSupport.signingKeyResolver(BaseVerifierBuilderSupport.java:166)
	at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build(JjwtAccessTokenVerifierBuilder.java:58)
	at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build(JjwtAccessTokenVerifierBuilder.java:27)
```

### Steps to reproduce

```
JwtVerifiers.accessTokenVerifierBuilder().setIssuer("https:/myissuer-domain.com/oauth2/default").setAudience("myaudience").build()
```

### Library Version
`0.5.7`

**Comment by nishant-mehta** [comment]
adding okthttp3 without exclusion fixes the issue.

````
      <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>
```

**Comment by nishant-mehta** [comment]
Added a PR https://github.com/okta/okta-jwt-verifier-java/pull/173 for this

**Comment by nishant-mehta** [comment]
When will new version be available?

**Comment by arvindkrishnakumar-okta** [comment]
Will get it out today. On Jan 22, 2024, at 4:19 PM, Nishant Mehta ***@***.***> wrote:﻿

This message originated outside your organization.
  

When will new version be available?

**Comment by arvindkrishnakumar-okta** [comment]
0.5.8 is available now.
