### ISSUE TITLE
Gradle shadowJar throws No `interface com.okta.jwt.AccessTokenVerifier$Builder` implementation found on the classpath.

### ISSUE THREAD

**Issue by abcfy2** [okta/okta-jwt-verifier-java#91]
### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

Do you have any gradle examples?

I try to use this in my gradle project:

```gradle
plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '6.1.0'
}

repositories {
    mavenCentral()
}

dependencies {
// ...
    implementation('com.okta.jwt:okta-jwt-verifier:0.5.1') {
        exclude group: 'org.slf4j'
    }
    runtimeOnly('com.okta.jwt:okta-jwt-verifier-impl:0.5.1') {
        exclude group: 'org.slf4j'
    }
}

shadowJar {
    archiveClassifier.set('')
    mergeServiceFiles()
}
```

But when I run my shadow jar will throws:

```
Caused by: java.lang.IllegalStateException: No `interface com.okta.jwt.AccessTokenVerifier$Builder` implementation found on the classpath. Have you remembered to include the okta-jwt-verifier-impl.jar in your runtime classpath?
        at com.okta.jwt.JwtVerifiers.lambda$loadService$1(JwtVerifiers.java:60)
        at <unknown class>.get(Unknown Source)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at com.okta.jwt.JwtVerifiers.loadService(JwtVerifiers.java:60)
        at com.okta.jwt.JwtVerifiers.accessTokenVerifierBuilder(JwtVerifiers.java:51)
        at id.attestation.plugins.auth.FacebookAuthService.<init>(FacebookAuthService.java:22)
        at java.base/java.lang.J9VMInternals.newInstanceImpl(Native Method)
        at java.base/java.lang.Class.newInstance(Class.java:2288)
        at org.pf4j.DefaultExtensionFactory.create(DefaultExtensionFactory.java:38)
        ... 30 common frames omitted
```

In fact `okta-jwt-verifier-impl` and services files already contains in shadow jar file:

```
META-INF/
META-INF/MANIFEST.MF
...
META-INF/okta/
META-INF/okta/version.properties
com/
com/okta/
com/okta/jwt/
com/okta/jwt/impl/
com/okta/jwt/impl/jjwt/
com/okta/jwt/impl/jjwt/BaseVerifierBuilderSupport.class
com/okta/jwt/impl/jjwt/TokenVerifierSupport.class
com/okta/jwt/impl/jjwt/TokenVerifierSupport$OktaJwtHandler.class
com/okta/jwt/impl/jjwt/ClaimsValidator$CompositeClaimsValidator.class
com/okta/jwt/impl/jjwt/ClaimsValidator.class
com/okta/jwt/impl/jjwt/ClaimsValidator$ContainsAudienceClaimsValidator.class
com/okta/jwt/impl/jjwt/IssuerMatchingSigningKeyResolver.class
com/okta/jwt/impl/jjwt/models/
com/okta/jwt/impl/jjwt/models/JwkKeys.class
com/okta/jwt/impl/jjwt/models/JwkKey.class
com/okta/jwt/impl/jjwt/JjwtAccessTokenVerifierBuilder.class
com/okta/jwt/impl/jjwt/RemoteJwkSigningKeyResolver.class
com/okta/jwt/impl/jjwt/JjwtIdTokenVerifier.class
com/okta/jwt/impl/jjwt/JjwtAccessTokenVerifier.class
com/okta/jwt/impl/jjwt/JjwtIdTokenVerifierBuilder.class
com/okta/jwt/impl/http/
com/okta/jwt/impl/http/HttpClient.class
com/okta/jwt/impl/http/OktaCommonsHttpClient.class
com/okta/jwt/impl/DefaultJwt.class
...
META-INF/services/com.okta.jwt.AccessTokenVerifier$Builder
META-INF/services/com.okta.jwt.IdTokenVerifier$Builder
META-INF/services/com.okta.commons.http.RequestExecutorFactory
META-INF/services/io.jsonwebtoken.CompressionCodec
META-INF/services/io.jsonwebtoken.io.Serializer
META-INF/services/io.jsonwebtoken.io.Deserializer
META-INF/services/com.fasterxml.jackson.core.JsonFactory
META-INF/services/com.fasterxml.jackson.core.ObjectCodec
...
```

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible.

### Library Version

0.5.1

**Comment by abcfy2** [comment]
Never mind, seems this is an pf4j issue

**Comment by rahmed14** [comment]
@abcfy2 
Hello, did you find a solution for this?

**Comment by bdemers** [comment]
@rahmed14 Can you include the details of the issue you are having?

**Comment by zahidmak** [comment]
@abcfy2 , how did you resolve this issue? If you don't mind, could you please share the solution?
